export enum Buttons {
	REPLY = 'REPLY',
	CLOSE = 'CLOSE',
	VIEW_CHAT_MESSAGES = 'VIEW_CHAT_MESSAGES',
	VIEW_PREVIOUS_CHATS = 'VIEW_PREVIOUS_CHATS',
	VIEW_MESSAGE_IMAGE = 'VIEW_MESSAGE_IMAGE',
}

export enum Selects {
	VIEW_CHAT_MESSAGES = 'VIEW_CHAT_MESSAGES',
}

export enum Modals {
	REPLY = 'REPLY',
	VIEW_MESSAGE_IMAGE = 'VIEW_MESSAGE_IMAGE',
}

export enum Errors {
	INVALID_MESSAGE_NUM,
	UNKNOWN,
}
